name: Build and Release

on:
  push:
    branches:
      - main  # Remplacez par la branche de votre choix

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get version
        id: package
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package.outputs.version }}
          release_name: ${{ steps.package.outputs.version }}
          body: |
            New changes are available
          draft: false
          prerelease: false

      - name: List all files in build directory
        id: list_files
        run: |
          echo "::set-output name=files::$(ls build)"

      - name: Upload files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/${{ steps.list_files.outputs.files }}
          asset_name: ${{ steps.list_files.outputs.files }}
          asset_content_type: application/octet-stream
      - name: Remove build directory
        run: |
          git rm -r build
          git commit -m "Remove build directory after release"
          git push origin main