name: Déploiement de l nouvelle version de l'application en release

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy Application
        run: npm run deploy
        env:
          NODE_ENV: production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
