name: Déploiement de la nouvelle version de l'application en release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:

      - name: Install dependencies
        run: npm install

      - name: Deploy application
        run: npm run deploy
        env:
          NODE_ENV: production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
