name: Build and Release

on:
  push:
    branches:
      - main  # Remplacez par la branche de votre choix

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set git user
        run: |
          git config --global user.email "davidcardigos@hotmail.fr"
          git config --global user.name "Davidcardig"

      - name: Get version
        id: package
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package.outputs.version }}
          release_name: ${{ steps.package.outputs.version }}
          body: |
            New changes are available
          draft: false
          prerelease: false

      - name: Upload all files in build directory
        run: |
          for file in build/*; do
            if [ -f "$file" ]; then
              echo "Uploading $file"
              encoded_name=$(jq -nr --arg name "$(basename "$file")" '$name|@uri')
              curl \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: $(file -b --mime-type "$file")" \
                --data-binary @"$file" \
                "${{ steps.create_release.outputs.upload_url }}?name=${encoded_name}"
            fi
          done
      - name: Remove build directory
        run: |
          git rm -r build
          git commit -m "Remove build directory after release"
          git push origin main