name: Déploiement de la nouvelle version de l'application en release

on:
  push:
    branches:
      - main

jobs:

  deploy:
      runs-on: windows-latest
      needs: build

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Set git user
          run: |
           git config --global user.email "davidcardigos@hotmail.fr"
           git config --global user.name "Davidcardig"

        - name: Install dependencies
          run: npm install

        - name: Build application
          run: npm run build
          env:
            NODE_ENV: production
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Verify dist-electron directory
          run: dir dist-electron

        - name: Deploy Application
          run: npm run deploy
          env:
            NODE_ENV: production
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
